services:
  # Next.js Web App & Telegram Bot (Combined)
  - type: web
    name: islomiy-hisobchi
    env: node
    plan: free
    buildCommand: pnpm install && pnpm --filter engine build && pnpm --filter web build
    startCommand: pnpm --filter web start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: BOT_TOKEN
        sync: false # Set in Dashboard
      - key: WEBAPP_URL
        fromService:
          type: web
          name: islomiy-hisobchi
          property: host
